CREATE TABLE brands (id_marca INTEGER,marca TEXT);
INSERT INTO brands (id_marca, marca) VALUES ('1', 'Fiat');
INSERT INTO brands (id_marca, marca) VALUES ('2', 'Volkswagen');
INSERT INTO brands (id_marca, marca) VALUES ('3', 'Kia');
INSERT INTO brands (id_marca, marca) VALUES ('4', 'Peugeot ');
INSERT INTO brands (id_marca, marca) VALUES ('5', 'Toyota');
INSERT INTO brands (id_marca, marca) VALUES ('6', 'Nissan');
INSERT INTO brands (id_marca, marca) VALUES ('7', 'Mitsubishi');
INSERT INTO brands (id_marca, marca) VALUES ('8', 'Subaru');
INSERT INTO brands (id_marca, marca) VALUES ('9', 'Chevrolet ');
INSERT INTO brands (id_marca, marca) VALUES ('10', 'JaC Motors');
INSERT INTO brands (id_marca, marca) VALUES ('11', 'Renault');